import image from "../assets/image.png";

export const cardsData = [
  {
    id: 1,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 2,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 3,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 4,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 5,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 6,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 7,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 8,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 9,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 10,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 11,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 12,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 13,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 14,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 15,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 16,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 17,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 18,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 19,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 20,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 21,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
  {
    id: 22,
    image: image,
    title: "Take Me Back",
    name: "Name Name",
    author: "Name",
    price: "000",
  },
];
